import {images} from '../images'

export default [
    {
        id: 1,
        name: "Johnny Depp",
        desc: "John Christopher Depp II (born June 9, 1963) is an American actor, producer, and musician. He is the recipient of multiple accolades, including a Golden Globe Award and a Screen Actors Guild Award, in addition to nominations for three Academy Awards and two BAFTA awards.",
        amount: "15000",
        amount1: "10000",
        img1: `${images.jo1}`,
        img2: `${images.jo2}`,
        img3: `${images.jo3}`,
        img4: `${images.jo4}`,
        img5: `${images.jo5}`,
        bio1: "John Christopher Depp II was born on June 9, 1963, in Owensboro, Kentucky, the youngest of four children of waitress Betty Sue Palmer (née Wells) and civil engineer John Christopher Depp.",
        bio2: "Depp's mother gave him a guitar when he was 12, and he began playing in various bands. He dropped out of Miramar High School at 16 in 1979 to become a rock musician.",
        fa: 'https://www.facebook.com/JohnnyDepp',
        tw: 'https://twitter.com/JohnnyDeppNFT',
        ig: 'https://www.instagram.com/johnnydepp/?hl=en',
    },
    {
        id: 2,
        name: "Jason Momoa",
        desc: "Joseph Jason Namakaeha Momoa (born August 1, 1979) is an American actor. He made his acting debut as Jason Loane on the syndicated action drama series Baywatch: Hawaii (1999–2001), which was followed by portrayals of Ronon Dex on the Syfy science fiction series Stargate Atlantis (2005–2009),",
        amount: "13000",
        amount1: "9000",
        img1: `${images.ja1}`,
        img2: `${images.ja2}`,
        img3: `${images.ja3}`,
        img4: `${images.ja4}`,
        img5: `${images.ja5}`,
        bio1: "An only child, Momoa was born on August 1, 1979, in Honolulu, Hawaii, to Coni (Lemke), a photographer, and Joseph Momoa, a painter. He moved with his mother to Norwalk, Iowa,",
        bio2: "At 19 years old, while living and working in Honolulu, Momoa decided to audition for the television series Baywatch Hawaii, in which he was cast as Jason Ioane (1999–2001)",
        fa: 'https://www.facebook.com/1JasonMomoaFans',
        tw: 'https://twitter.com/jasonmomoa_th?lang=en',
        ig: 'https://www.instagram.com/prideofgypsies/',
    },
    {
        id: 3,
        name: "Henry Cavill",
        desc: "Henry William Dalgliesh Cavill (/ˈkævəl/; born 5 May 1983) is a British actor. He is known for his portrayal of Charles Brandon in Showtime's The Tudors (2007–2010), DC Comics character Superman in the DC Extended Universe, Geralt of Rivia in the Netflix fantasy series The Witcher (2019–present)",
        amount: "12500",
        amount1: "7000",
        img1: `${images.ca1}`,
        img2: `${images.ca2}`,
        img3: `${images.ca3}`,
        img4: `${images.ca4}`,
        img5: `${images.ca5}`,
        bio1: "Cavill was born on 5 May 1983, the fourth of five boys in a Roman Catholic family at Saint Helier, Jersey, in the Channel Islands. His mother, Marianne Dalgliesh, was a secretary in a bank. ",
        bio2: "Cavill began his film career with a role in Laguna (2001) and Kevin Reynolds' adaptation of The Count of Monte Cristo (2002). He continued with appearances in BBC's The Inspector Lynley Mysteries (2002). ",
        fa: 'https://www.facebook.com/henrycavill',
        tw: '#',
        ig: 'https://www.instagram.com/henrycavill/?hl=en',
    },
    {
       
        id: 4,
        name: "Ian Somerhalder",
        desc: "Ian Joseph Somerhalder (born December 8, 1978) is an American actor, model, and activist. He is known for playing Boone Carlyle in the TV drama Lost, Damon Salvatore in The CW's supernatural drama The Vampire Diaries and Dr. Luther Swann in Netflix's sci-fi horror series V Wars.",
        amount: "10500",
        amount1: "6000",
        img1: `${images.ia1}`,
        img2: `${images.ia2}`,
        img3: `${images.ia3}`,
        img4: `${images.ia4}`,
        img5: `${images.ia5}`,
        bio1: "Somerhalder was born and raised in Covington, Louisiana, the son of Edna, a massage therapist, and Robert Somerhalder, an independent building contractor. He is the second of three children, with an older brother, Robert, and younger sister, Robyn.",
        bio2: "In the summer of 2000, Somerhalder starred in the short-lived WB series Young Americans, a spin-off of Dawson's Creek. He played Hamilton Fleming, the son of the dean of a prestigious boarding school.",
        fa: 'https://www.facebook.com/iansomerhalderofficial',
        tw: 'https://twitter.com/iansomerhalder?lang=en',
        ig: 'https://www.instagram.com/iansomerhalder/?hl=en',
    },
    {
        id: 5,
        name: "Luke Bryan",
        desc: "Thomas Luther 'Luke' Bryan (born July 17, 1976) is an American country singer and songwriter. He began his music career writing songs for Travis Tritt and Billy Currington before signing with Capitol Nashville in 2007. He is one of the most successful and awarded country artists of the 2010s and 2020s.",
        amount: "11500",
        amount1: "7000",
        img1: `${images.br1}`,
        img2: `${images.br2}`,
        img3: `${images.br3}`,
        img4: `${images.br4}`,
        img5: `${images.br5}`,
        bio1: "Luke Bryan was born in Leesburg, Georgia, to LeClaire and Tommy Bryan, a peanut farmer. Shortly before Luke was going to move to Nashville at age 19, his elder brother Chris was unexpectedly killed in a car accident .",
        bio2: "Instead, Luke went to college at Georgia Southern University in Statesboro, Georgia, where he joined the Sigma Chi fraternity and graduated in 1999 with a bachelor's degree in business administration. ",
        fa: 'https://www.facebook.com/lukebryan',
        tw: 'https://twitter.com/lukebryan?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        ig: 'https://www.instagram.com/lukebryan/?hl=en',
    },
    {
       
        id: 6,
        name: "Jensen Ackles",
        desc: "Jensen Ross Ackles (born March 1, 1978) is an American actor. He is best known for his portrayal of Dean Winchester in The WB/CW dark fantasy drama series Supernatural (2005-2020) and appearing in television series such as NBC’s Days of Our Lives as Eric Brady (earning him several Daytime Emmy Award nominations).",
        amount: "13500",
        amount1: "8000",
        img1: `${images.je1}`,
        img2: `${images.je2}`,
        img3: `${images.je3}`,
        img4: `${images.je4}`,
        img5: `${images.je5}`,
        bio1: "Ackles was born in Dallas the son of Donna Joan (née Shaffer) and Alan Roger Ackles, an actor. He grew up in Richardson and attended Lloyd V. Berkner High School. After graduating in 1996, he moved to Los Angeles to begin his acting career.",
        bio2: "After modeling on and off since the age of four, Ackles began to concentrate on an acting career in 1996. He appeared in several guest roles on Mr. Rhodes, Sweet Valley High, and Cybill before joining the cast of the NBC soap opera Days of Our Lives as Eric Brady in 1997. ",
        fa: 'https://www.facebook.com/JensenAckles',
        tw: 'https://twitter.com/jensenackles',
        ig: 'https://www.instagram.com/jensenackles/?hl=en',
    },
    {
        id: 7,
        name: "Kit Harrington",
        desc: "Christopher Catesby Harington (born 26 December 1986) is an English actor. He studied at the Royal Central School of Speech and Drama and made his professional acting debut with the lead role of Albert Narracott in the West End play War Horse in 2009. In 2011, his breakthrough role as Jon Snow in the HBO epic fantasy television series Game of Thrones",
        amount: "13500",
        amount1: "7500",
        img1: `${images.ki1}`,
        img2: `${images.ki2}`,
        img3: `${images.ki3}`,
        img4: `${images.ki4}`,
        img5: `${images.ki5}`,
        bio1: "Christopher Catesby Harington was born on 26 December 1986 in Acton, London. His mother named him after Christopher Marlowe, whose first name was shortened to Kit, a name Harington prefers. He did not learn what his full name was until he was eleven years old. ",
        bio2: "Harington was a pupil at the Southfield Primary School from 1992 to 1998. When he was 11, his family moved to Worcestershire and he studied at the Chantry High School in Martley until 2003. He became interested in acting after watching a production of Waiting for Godot when he was 14. ",
        fa: 'https://www.facebook.com/JensenAckles',
        tw: 'https://twitter.com/jensenackles',
        ig: 'https://www.instagram.com/jensenackles/?hl=en',
    },
    {
        id: 8,
        name: "Patrick Dempsey",
        desc: "Patrick Galen Dempsey (born January 13, 1966) is an American actor and race car driver, best known for his role as neurosurgeon Derek 'McDreamy' Shepherd in Grey's Anatomy. He had early success as an actor, starring in a number of films in the 1980s, including Can't Buy Me Love (1987) and Loverboy (1989). In the 1990s, he mostly appeared in smaller roles in film.",
        amount: "12500",
        amount1: "8500",
        img1: `${images.de1}`,
        img2: `${images.de2}`,
        img3: `${images.de3}`,
        img4: `${images.de4}`,
        img5: `${images.de5}`,
        bio1: "Dempsey was born in Lewiston, Maine, and grew up in the nearby towns of Turner and Buckfield. He has two older sisters and a half-brother, Shane Wray. His mother, Amanda (née Casson), was a school secretary, and his father, William, was an insurance salesman.",
        bio2: "An invitation to audition for a role in the stage production of Torch Song Trilogy led to Patrick Dempsey's discovery as an actor. His audition was successful and he spent the following four months touring with the company in Philadelphia. He followed this with another tour, Brighton Beach Memoirs.",
        fa: 'https://www.facebook.com/patrickdempseyofficial',
        tw: 'https://twitter.com/patrickdempsey',
        ig: 'https://www.instagram.com/patrickdempsey/?hl=en',
    },
    {
        id: 9,
        name: "Denzel Washington",
        desc: "Denzel Hayes Washington Jr. (born December 28, 1954) is an American actor, director, and producer. Known for his performances on the screen and stage, he has been described as an actor who reconfigured 'the concept of classic movie stardom'. He is also known for his frequent collaborations with directors Spike Lee, Antoine Fuqua, and Tony Scott.",
        amount: "14000",
        amount1: "9500",
        img1: `${images.wa1}`,
        img2: `${images.wa2}`,
        img3: `${images.wa3}`,
        img4: `${images.wa4}`,
        img5: `${images.wa5}`,
        bio1: "Denzel Hayes Washington Jr. was born in Mount Vernon, New York, on December 28, 1954. His mother, Lennis 'Lynne', was a beauty parlor owner and operator born in Georgia and partly raised in Harlem, New York. His father, Denzel Hayes Washington Sr., a native of Buckingham County, Virginia, was an ordained Pentecostal minister.",
        bio2: "Washington attended Pennington-Grimes Elementary School in Mount Vernon until 1968. When he was 14, his parents divorced and his mother sent him to the private preparatory school Oakland Military Academy in New Windsor, New York. Washington later said, 'That decision changed my life, because I wouldn't have survived in the direction I was going. ",
        fa: 'https://www.facebook.com/Denzel-Washington-Actor-1655621238031573/',
        tw: 'https://twitter.com/officiaidenzei?lang=en',
        ig: 'https://www.instagram.com/denzelwashington.official/?hl=en',
    },
    {
        id: 10,
        name: "Chris Evans",
        desc: "Christopher Robert Evans (born June 13, 1981) is an American actor. He began his career with roles in television series, such as in Opposite Sex in 2000. Following appearances in several teen films including 2001's Not Another Teen Movie, he gained attention for his portrayal of Marvel Comics character the Human Torch in Fantastic Four (2005) and Fantastic Four",
        amount: "13000",
        amount1: "8500",
        img1: `${images.ch1}`,
        img2: `${images.ch2}`,
        img3: `${images.ch3}`,
        img4: `${images.ch4}`,
        img5: `${images.ch5}`,
        bio1: "Christopher Robert Evans was born on June 13, 1981, in Boston, Massachusetts, and grew up in the nearby town of Sudbury. His mother, Lisa (née Capuano), is an artistic director at the Concord Youth Theater, and his father, Bob, is a dentist. His parents divorced in 1999.",
        bio2: "Evans has two sisters, Carly and Shanna, and a brother, actor Scott Evans. He and his siblings were raised Catholic. Their uncle, Mike Capuano, represented Massachusetts's 8th congressional district. Evans has Irish, and from his maternal grandfather, Italian, ancestry.",
        fa: 'https://www.facebook.com/search/top/?q=Chris+Evans',
        tw: 'https://twitter.com/ChrisEvans?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        ig: 'https://www.instagram.com/chrisevans/?hl=en',
    },
    {
        id: 11,
        name: "Brad Pitt",
        desc: "William Bradley Pitt (born December 18, 1963) is an American actor and film producer. He is the recipient of various accolades, including an Academy Award, a British Academy Film Award, two Golden Globe Awards, two Screen Actors Guild Award and a Primetime Emmy Award. In 2001, Pitt co-founded the production company, Plan B Entertainment which has produced various films",
        amount: "13000",
        amount1: "9500",
        img1: `${images.pi1}`,
        img2: `${images.pi2}`,
        img3: `${images.pi3}`,
        img4: `${images.pi4}`,
        img5: `${images.pi5}`,
        bio1: "William Bradley Pitt was born on December 18, 1963, in Shawnee, Oklahoma, to William Alvin Pitt, the proprietor of a trucking company, and Jane Etta (née Hillhouse), a school counselor. ",
        bio2: "Pitt is very distantly related to the 44th president of the United States, Barack Obama. The two have a common ancestor from the 18th century named Edwin Hickman.",
        fa: 'https://www.facebook.com/profile.php?id=100044628330280',
        tw: '#',
        ig: 'https://www.instagram.com/bradpittofflcial/?hl=en',
    },
    {
        id: 12,
        name: "Bradley Cooper",
        desc: "Bradley Charles Cooper (born January 5, 1975) is an American actor and filmmaker. He is the recipient of various accolades, including a British Academy Film Award and two Grammy Awards, in addition to nominations for nine Academy Awards, six Golden Globe Awards, and a Tony Award. Cooper appeared on the Forbes Celebrity 100 three times and on Time's list of the 100 most influential people in the world in 2015.",
        amount: "13500",
        amount1: "8500",
        img1: `${images.co1}`,
        img2: `${images.co2}`,
        img3: `${images.co3}`,
        img4: `${images.co4}`,
        img5: `${images.co5}`,
        bio1: "Cooper was born on January 5, 1975, in Abington Township, near Philadelphia, and grew up in the nearby communities of Jenkintown and Rydal. His mother, Gloria (née Campano), worked for the local NBC affiliate. ",
        bio2: "Describing himself as a child, Cooper has said: 'I never lived the life of 'Oh, you're so good-looking'. People thought I was a girl when I was little, because I looked like a girl—maybe because my mother would keep my hair really long'.",
        fa: '#',
        tw: '#',
        ig: 'https://www.instagram.com/bradleycooper__original/?hl=en',
    },
    
    {
        id: 13,
        name: "Thomas Mark Harmon",
        desc: "Thomas Mark Harmon (born September 2, 1951) is an American actor. He is most famous for playing the lead role of Leroy Jethro Gibbs in NCIS. He also has appeared in a wide variety of roles since the early 1970s. Initially a college football player, he was named 'Sexiest Man Alive' by People magazine in 1986, due largely to his role as Dr. Robert Caldwell on St. Elsewhere, a role notable for being one of the first TV characters that had HIV.",
        amount: "12500",
        amount1: "7500",
        img1: `${images.th1}`,
        img2: `${images.th2}`,
        img3: `${images.th3}`,
        img4: `${images.th4}`,
        img5: `${images.th5}`,
        bio1: "Harmon was born in Burbank, California, the youngest of three children. His parents were Heisman Trophy–winning football player and broadcaster Tom Harmon and actress, model, and artist Elyse Knox (née Elsie Lillian Kornbrath). ",
        bio2: "He was inducted into the inaugural class of the Pierce College Athletic Hall of Fame in 2010.",
        fa: '#',
        tw: '#',
        ig: '#',
    },
  
];
